### ISSUE TITLE
About the mesh reconstruction part

### ISSUE THREAD

**Issue by kyewong** [ScanNet/ScanNet#11]
The mesh reconstruction result seems fantastic. Did you use 3DLite to finish the mesh reconstruction part on the cloud? Is there any plan to open source that part pls?

**Comment by msavva** [comment]
The mesh reconstruction was done with the [BundleFusion](http://graphics.stanford.edu/projects/bundlefusion/) system which is already open sourced.  Please refer to the BundleFusion project website for details on how to use the code.
