### ISSUE TITLE
Can't download color, depth, intrinsic, pose

### ISSUE THREAD

**Issue by BlarkLee** [ScanNet/ScanNet#110]
Hi,

When I used the python downloading code to download the dataset in March, it has color, depth, intrinsic, pose folder with the .sen files, today when I tried to download more date, the color, depth, intrinsic, pose folders cannot be downloaded with .sen files, even cannot without any --type specification, is there any update to the dataset downloader?

**Comment by DarKayserLeo** [comment]
Hi, do you know how to fix this? I have the same issue and need those folders for this project: https://github.com/noahstier/vortx

**Comment by DarKayserLeo** [comment]
> Hi, do you know how to fix this? I have the same issue and need those folders for this project: https://github.com/noahstier/vortx

Hi, do you know how to fix this? I have the same issue and need those folders for this project: https://github.com/noahstier/vortx
