### ISSUE TITLE
Can not download the data

### ISSUE THREAD

**Issue by eslambakr** [ScanNet/ScanNet#114]
Dears,

Thanks for your amazing work!

While I am trying to download the data on a new machine I faced the following error 
"IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)" 
Despite I downloaded it two days ago successfully

Thanks in advance!

**Comment by eslambakr** [comment]
It was my fault.
Sorry for disturbing you.

**Comment by Quyans** [comment]
> It was my fault. Sorry for disturbing you.

hi， how did you fix the problem? I met the same problem, it seems like the download server is broken
