### ISSUE TITLE
Possible SensReader Python Issue

### ISSUE THREAD

**Issue by BillyXYB** [ScanNet/ScanNet#115]
Hi I encountered "TypeError: sequence item 0: expected str instance, bytes found" in  https://github.com/ScanNet/ScanNet/blob/84178a87713b517dfdb05e0b7056493a627c24ff/SensReader/python/SensorData.py#L58
and if comment that line, I got KeyError: 1065353216"  in https://github.com/ScanNet/ScanNet/blob/84178a87713b517dfdb05e0b7056493a627c24ff/SensReader/python/SensorData.py#L73
The scan I tested was scene0000_00

**Comment by lahavlipson** [comment]
Did you resolve the issue?

**Comment by GetOverMassif** [comment]
> Hi I encountered "TypeError: sequence item 0: expected str instance, bytes found" in
> 
> https://github.com/ScanNet/ScanNet/blob/84178a87713b517dfdb05e0b7056493a627c24ff/SensReader/python/SensorData.py#L58
> 
> 
> and if comment that line, I got KeyError: 1065353216" in
> https://github.com/ScanNet/ScanNet/blob/84178a87713b517dfdb05e0b7056493a627c24ff/SensReader/python/SensorData.py#L73
> 
> 
> The scan I tested was scene0000_00

I made the following changes and the data was successfully parsed:
- exchange all `''.join` with `b''.join`
- exchange all `print a,b,c...` with `print(a,b,c...)`
- echange `[struct.unpack('i', f.read(4))[0]]` with `[int(struct.unpack('i', f.read(4))[0])]`
