### ISSUE TITLE
When testing the benchmark, I encountered the problem of Could not archive the uploaded file. How to solve it?

### ISSUE THREAD

**Issue by xiaoyangyang123** [ScanNet/ScanNet#129]
When testing the benchmark, I encountered the problem of Could not archive the uploaded file. How to solve it?

**Comment by JLUtangchuan** [comment]
Hello, have you solve this problem?

**Comment by fanyan121212** [comment]
I uploaded the results four days ago, but the evaluation failed.  
The benchmark administrator informed me the reason for that is: The evaluation script encountered a problem.

**Comment by xiaoyangyang123** [comment]
> 您好，您解决了这个问题吗？

it's OK now

**Comment by xiaoyangyang123** [comment]
> 我在四天前上传了结果，但评估失败。基准测试管理员告诉我原因是：评估脚本遇到问题。

I've been running into this problem all the time: Invalid Submission: Submissions must have meaningful names (ie, the full name should be similar to the paper title).

**Comment by fanyan121212** [comment]
So your evaluation has succeeded?

**Comment by fanyan121212** [comment]
Now they inform me that:

Unfortunately, our evaluation system failed to evaluate your result submission for xxx.
Reason: Extraction of the submitted archive failed.

The system thinks that the problem is due to invalid input.

I am not sure if it's my problem or not, so please let me know if you succeeded.

**Comment by JLUtangchuan** [comment]
I met the same problem.  Submission failed.

**Comment by xiaoyangyang123** [comment]
> 我遇到了同样的问题。提交失败。

I changed the name to the full name of my paper and the submission was successful

**Comment by lishawa** [comment]
> > 现在他们告诉我：
> > 很遗憾，我们的评估系统未能评估您提交的 xxx 结果。原因：提取提交的存档失败。
> > 系统认为问题是由于输入无效造成的。
> > 我不确定这是否是我的问题，所以如果你成功了，请告诉我。
> 
> I changed the name to the full name of my paper and the submission was successful

The same problem. However, the submission shows that full method name cannot be edited. How to solve it?
