### ISSUE TITLE
exported PNG file is not recognized

### ISSUE THREAD

**Issue by bloodhunt3r** [ScanNet/ScanNet#148]
When I load the 16 bit png file 

```python
res = cv2.imread("/media/ran/Data/Datasets/ScanNet/scans/scene0000_01/depth/0.png", -1)
```

it shows the following error:

```sh
libpng error: bad adaptive filter value
```

**Comment by bloodhunt3r** [comment]
solved it by upgrading the pypng to `0.0.20`

```sh
pip install pypng==0.0.20
```

**Comment by LiangXu123** [comment]
> solved it by upgrading the pypng to `0.0.20`
> 
> ```shell
> pip install pypng==0.0.20
> ```

did not work for python 3.8 + opencv 3.4.8

**Comment by shjung13** [comment]
Hi @LiangXu123, In my case, this problem was solved by using this script using python3: https://github.com/pengsongyou/openscene/blob/main/scripts/preprocess/scannet_sensordata.py.

**Comment by LiangXu123** [comment]
> Hi @LiangXu123, In my case, this problem was solved by using this script using python3: https://github.com/pengsongyou/openscene/blob/main/scripts/preprocess/scannet_sensordata.py.

thanks，I solved it by uncomment this line :https://github.com/ScanNet/ScanNet/blob/fcaa1773a9e186b22a4228df632b6999a1633b79/SensReader/python/SensorData.py#L87
and comment the following 4 lines.

and I works fine now.
