### ISSUE TITLE
Intrinsic of aligned image

### ISSUE THREAD

**Issue by tymanab** [ScanNet/ScanNet#161]
Hi, 
I'm working on a 3D reconstruction project that requires color image has same resolution with depth image. According to #28 and #92, it is possible to get aligned RGB-D image by resize color image to 640x480. However, I have a question regarding to the use of intrinsics. Should I use depth intrinsics for both color and depth images after resizing, considering that they are already aligned at pixel level?

**Comment by guker** [comment]
Hello,  I have same question  with you,   have you sloved it?

**Comment by tymanab** [comment]
Well, I just resize and use it without further checking. If you want to validate whether this works, maybe could try back project the resized image to original mesh.

**Comment by guker** [comment]
> Well, I just resize and use it without further checking. If you want to validate whether this works, maybe could try back project the resized image to original mesh.

ok，if resizing color image to 640x480,  which intrinsics (depth intrinsics and color intrinsics) should i use?
