### ISSUE TITLE
i tray to run create_data.py,but file can't find

### ISSUE THREAD

**Issue by shaonianG** [ScanNet/ScanNet#167]
i have download scanet,the struct is
<img width="419" alt="image" src="https://github.com/user-attachments/assets/c1e39f9b-1278-42e8-8a3f-dfa4be2cfbfb">
then i try to run program
`python tools/create_data.py scannet --root-path ./data/scannet --out-dir ./data/scannet --extra-tag scannet`
,but
FileNotFoundError: [Errno 2] No such file or directory: '.\\data\\scannet\\scannet_instance_data\\scene0191_00_vert.npy'
<img width="562" alt="image" src="https://github.com/user-attachments/assets/3a0f07b4-1aa6-49f5-88cc-8d8474073b73">
i search my computer,but cant find scannet_instance_data or scene0191_00_vert.npy,so,may be my data set is not compelete?

**Comment by xueboyang** [comment]
you can try to move the 'scans_test' folder to the same level of directory
