### ISSUE TITLE
Color Point Mapping To Depth Point

### ISSUE THREAD

**Issue by gfsliumin** [ScanNet/ScanNet#2]
Hi,
can you show me how to map color point to depth point, since the resolution of color images and depth images is different?
Thanks a lot!

**Comment by angeladai** [comment]
The color and depth images are aligned, so they can be resampled to the same resolution

**Comment by gfsliumin** [comment]
Thanks!

**Comment by mangdian** [comment]
@gfsliumin @angeladai Hi, I am now using the dataset for depth estimation. So all I need to do is extract the depth and RGB image, and resize them to the same resolution?

**Comment by kong-johnny** [comment]
> The color and depth images are aligned, so they can be resampled to the same resolution

But the intrinsic parameters of color and depth images are different, are you sure that they are aligned?

**Comment by guker** [comment]
> > The color and depth images are aligned, so they can be resampled to the same resolution
> 
> But the intrinsic parameters of color and depth images are different, are you sure that they are aligned?

I have same question for you， have you solved it？

**Comment by guker** [comment]
> > The color and depth images are aligned, so they can be resampled to the same resolution
> 
> But the intrinsic parameters of color and depth images are different, are you sure that they are aligned?

I have same questions,  have you sloved it？
