### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by yzp12** [ScanNet/ScanNet#21]
I have trouble download the data using the provided script. Seems the server is down?

**Comment by vevenom** [comment]
I have been experiencing the same issue. It seems that the server is indeed down :/

From other issues, it seems there  are more people affected by this:

> can you download the datasets? when I run the script, it occurs "urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>"

**Comment by angeladai** [comment]
Please contact the googlegroups.
