### ISSUE TITLE
Possible bug in the instance segmentation evaluation script

### ISSUE THREAD

**Issue by charlesq34** [ScanNet/ScanNet#23]
While examining `evaluate_semantic_instance.py` I found a possible bug:

https://github.com/ScanNet/ScanNet/blob/fc255fefa3918a21930681ce7c52502a4447c228/BenchmarkScripts/3d_evaluation/evaluate_semantic_instance.py#L267

I believe that the `gt_ids` are label_id*1000+inst_id, however the VALID_CLASS_IDS are just label_ids, so the `bool_void` will always be all zeros. Besides the current formula seems to compute the non-void mask. The right way to compute `bool_void` is probably: 

`bool_void = np.logical_not(np.in1d((gt_ids/1000).astype(np.int32), VALID_CLASS_IDS))`

This bug may not affect the result too much but should be fixed.

**Comment by angeladai** [comment]
Fixed in https://github.com/ScanNet/ScanNet/commit/a3c66b48f6c6c8d64e8b2b25b4f0ae2ffc75252d

**Comment by LZDSJTU** [comment]
I do not understand why gt_ids == label_id*1000+inst_id. I do not find the function to define this.

**Comment by LZDSJTU** [comment]
So maybe I understand. I misunderstood the format of gt_file.

gt_file should be a txt with one integer each line. And The integer should be equal to label_id*1000+inst_id.

Do I understand rightly? So if we want to evaluate, we need to generate the gt_file by ourselves?

**Comment by LZDSJTU** [comment]
> @LZDSJTU right. the format of the GT file for instance segmentation is different from the PREDICTION files. You have to generate the GT files by yourself.

Yep, and I have generated the GT file by myself. But I have a question that how you know that gt_file should be like "label_id*1000+inst_id". I do not find this in the scannet scripts.

Is this your guess according to the evaluate scripts?

**Comment by charlesq34** [comment]
@LZDSJTU you can see in the evaluation script the GT_FILE is loaded by the `load_ids` function and then fed into `util_3d.get_instances` which then calls the `Instance` class initialization which assumes the id to be label_id*1000+inst_id.

https://github.com/ScanNet/ScanNet/blob/981e988ec24051ad1ad0a0770bd1b8c42c82084e/BenchmarkScripts/3d_evaluation/evaluate_semantic_instance.py#L251

**Comment by lapetite123** [comment]
Hello, I use this command to generate the instance gt-file "python export_train_mesh_for_evaluation.py --scan_path /home/data/scannetv2/scans/scene0000_00 --output_file /home/data/scannetv2/output.txt  --label_map_file /home/data/scannetv2/scannetv2-labels.combined.tsv --type instance",
and I get the gt file like this:
pred_mask/output_1.txt 9 1.000000
pred_mask/output_2.txt 9 1.000000
pred_mask/output_3.txt 7 1.000000
pred_mask/output_4.txt 12 1.000000
pred_mask/output_5.txt 38 1.000000
pred_mask/output_6.txt 16 1.000000
pred_mask/output_7.txt 16 1.000000
pred_mask/output_8.txt 14 1.000000
pred_mask/output_9.txt 3 1.000000

I am not sure whether this is correct, waiting for your reply

**Comment by lapetite123** [comment]
@LZDSJTU hello, the gt file should be gt_ids == label_id*1000+inst_id, what does  the label_id and ins_id mean? As you mentioned above,  gt_file should be a txt with one integer each line, but the ins gt file I generate like "pred_mask/output_1.txt 9 1.000000", can you tell me how to generate instance ground truth file? I really hope to get your help! thanks!
