### ISSUE TITLE
Align Color to Depth (640x480) 

### ISSUE THREAD

**Issue by LittleLampChen** [ScanNet/ScanNet#28]
Hello, how can I align color image to depth image in these scenes?
Can I just simply resize the color image to 640x480?

**Comment by CaptainTrunky** [comment]
In general, no, you can't. Consider scene0000_01/frame_2481. The bicycle's tire would be partially colored as a floor. So you should align both images. However, as far as I understand, there is not enough data to align images automatically.

**Comment by LittleLampChen** [comment]
Thanks!

**Comment by mangdian** [comment]
@CaptainTrunky Hi, what do you mean by "both cameras aligned already"? We can assume the depth and colored image are already aligned?

**Comment by CaptainTrunky** [comment]
> @CaptainTrunky Hi, what do you mean by "both cameras aligned already"? We can assume the depth and colored image are already aligned?

As far as I remember, yes, we can assume that.

**Comment by mangdian** [comment]
@CaptainTrunky So we can directly resize the depth and colored image to the same resolution, and use them for training? That would be much easier. Thanks a lot.

**Comment by densechen** [comment]
@mangdian If you just use rgbd as input, just scale them to the size you wanted. That should be OK. But, if you want to convert the depth to xyz, you should first convert them in original depth image, them get three channels xyz map, and do scale on it. It should be ok. 
If you scale the image, the intrinsic is changed.

**Comment by mangdian** [comment]
@densechen I am now using ScanNet for depth estimation, so I can scale both depth and colored image to the target size without aligning them in the xyz space?

**Comment by CaptainTrunky** [comment]
> @densechen I am now using ScanNet for depth estimation, so I can scale both depth and colored image to the target size without aligning them in the xyz space?

Yes, you could consider them aligned already.
