### ISSUE TITLE
The visualisation of Voxel dataset  

### ISSUE THREAD

**Issue by yxliwhu** [ScanNet/ScanNet#4]
@msavva Could you tell me which software is used for the visualisation of voxel dataset in the paper? Thank you.

**Comment by msavva** [comment]
We used the [Mitsuba](https://www.mitsuba-renderer.org) raytracer to render the voxel visualizations.  More specifically, the voxel grids were exported as PLY format mesh files where each occupied voxel is a cube, and then the meshes were provided as input to a [python rendering script](https://gist.github.com/msavva/1d1d589c8f39c4c46465a3b9cc9978bf). Please note that the rendering script requires the Mitsuba python wrapper API to be installed and in the path.

**Comment by hongxiaoy** [comment]
> itsuba python wrapper API to be installed and in the path.

Is the voxel dataset still available? Thanks.
