### ISSUE TITLE
Where are the GroudTruth of 3D Semantic instance benchmark ?

### ISSUE THREAD

**Issue by wusuoweima** [ScanNet/ScanNet#43]
I can not find the GroudTruth of 3D Semantic instance task, where are they? Thank you very much.

**Comment by angeladai** [comment]
For the scannet benchmark, results can be evaluated on the online benchmark; ground truth is hidden to provide as fair comparisons as possible.

**Comment by lapetite123** [comment]
where to evaluated the hidden test AP, can you give me a link?
