### ISSUE TITLE
aggregation index out of range

### ISSUE THREAD

**Issue by qq456cvb** [ScanNet/ScanNet#47]
I am reading <scanId>_vh_clean.aggregation.json for a per point annotation, however, for scene train/ 0002_00, I got the following error:  index 307925 is out of bounds for axis 1 with size 297362. It seems that the index stored in aggregation.json exceeds the total number of points.

**Comment by qq456cvb** [comment]
I misunderstood the file, the idx is actually stored in _vh_clean_2.0.010000.segs.json. Closing this.

**Comment by ZhengdiYu** [comment]
Hey,  Is the per-point annotations you mentioned instance labels? What is the differences between '.segs.json' and '.aggregation.json'. Thank you very much!

**Comment by ZhengdiYu** [comment]
It seems that there are segments indices in '.segs.json', and we can get corresponding instance id in '.aggregation.json' through the segments id.

However the total number of segments id is not consistent with those in '.aggregation.json'. Is these the segments without annotation?

**Comment by zyoungDL** [comment]
Could you tell me how to get instance label of each point from '.segs.json' and '.aggregation.json'.

**Comment by zyoungDL** [comment]
Thanks a lot.

**Comment by zyoungDL** [comment]
> It seems that there are segments indices in '.segs.json', and we can get corresponding instance id in '.aggregation.json' through the segments id.
> 
> However the total number of segments id is not consistent with those in '.aggregation.json'. Is these the segments without annotation?

Could you tell me how to get instance label of each point from '.segs.json' and '.aggregation.json'. Thanks a lot.

**Comment by qq456cvb** [comment]
From what I remember, every object is composed of several segments, where each segment is assigned a unique ID, stored in ‘segs.json’. ‘.aggregation.json’ (perhaps, I am not sure) stores the segment IDs that every instance contains. Then the instances can be labeled by those segments.

**Comment by MushroomLyn** [comment]
> It seems that there are segments indices in '.segs.json', and we can get corresponding instance id in '.aggregation.json' through the segments id.
> 
> However the total number of segments id is not consistent with those in '.aggregation.json'. Is these the segments without annotation?

I also doubt that some segments don't have labels.
