### ISSUE TITLE
Cannot create a new submission on ScanNet public benchmark

### ISSUE THREAD

**Issue by jytime** [ScanNet/ScanNet#52]
Hi all,

I was hoping if anyone meets the problem when uploading results into the [ScanNet benchmark ](http://kaldir.vc.in.tum.de/scannet_benchmark/). I have successfully created an account and am trying to submit my 3D instance segmentation results. 

However, after filling the information required in the 'Create New Submission' page and clicking on the 'Save' button, the website always returns "This page isn't working; kaldir.vc.in.tum.de is currently unable to handle this request. Http Error 500". Has anyone encountered this problem? Any comments are welcome.

Best,
Jianyuan

**Comment by zhangguanghui1** [comment]
Me too.I also encountered this problem. Have you solve it? Thank you so much.

**Comment by zhangguanghui1** [comment]
@jytime Me too.I also encountered this problem. Have you solve it? Thank you so much.
