### ISSUE TITLE
Registering depth maps to world point cloud

### ISSUE THREAD

**Issue by ishanic** [ScanNet/ScanNet#68]
Hello,

I am trying to compute a combined point cloud by aggregating depth maps across all cameras.
After unprojecting depth [X_i,Y_i,Z_i] = unproject(depth_i), each point cloud needs to be transformed by the camera pose to get the world coordinates - [X_i,Y_i,Z_i].transform(camera_pose_i). Similarly for frame j: [X_j,Y_j,Z_j].transform(camera_pose_j). I was expecting that projecting these two point clouds would lead to perfectly aligned clouds. Am I missing something?

**Comment by Cuistiano** [comment]
Hello, I met the same problem as you. Could you tell me how did you solve this problem? Thank you!

**Comment by FomalhautB** [comment]
I am also having the same issue

**Comment by FomalhautB** [comment]
I solved the problem. Here is my code: #98
