### ISSUE TITLE
scans_test of _2d-label.zip and _2d-label-filt.zip is all empty

### ISSUE THREAD

**Issue by qiminchen** [ScanNet/ScanNet#73]
as title, all the folders (scene0707_00 to scene0806_00) under the scans_test are empty, and in the `task/scannet_frames_test`, it's color, depth and pose, not ground truth 2d labels. Where can I find the test data for 2d label segmentation?

**Comment by JamesMcCullochDickens** [comment]
@qiminchen how did you solve this?
