### ISSUE TITLE
Can't browse and query Scannet data online!

### ISSUE THREAD

**Issue by dcy0577** [ScanNet/ScanNet#79]
Hello,
@angeladai These two links are not available on Scannet website:

http://kaldir.vc.in.tum.de/scannet_browse/scans/scannet/querier
http://kaldir.vc.in.tum.de/scannet_browse/scans/scannet/grouped
![image](https://user-images.githubusercontent.com/50020414/110130544-6c12c500-7dc9-11eb-88a9-1f7404db6eaf.png)

I would like to check whether some certain object labels are contained in the scans before downloading them. Are there any possibilities to do that besides querying data online?

**Comment by angeladai** [comment]
browser should work now
