### ISSUE TITLE
What does AP stand for?

### ISSUE THREAD

**Issue by rcffc** [ScanNet/ScanNet#80]
In the [3D Semantic instance benchmark](http://kaldir.vc.in.tum.de/scannet_benchmark/semantic_instance_3d.php?metric=ap) there are three metrics listed: AP, AP25%, AP50%.

The numbers in AP25% and AP50% I understand as IoU percentage.
But what does the plain AP mean? It is not explained anywhere.

Thanks for your time.

**Comment by angrypiggy** [comment]
Average Precision
