### ISSUE TITLE
Server down or maintenance

### ISSUE THREAD

**Issue by angrypiggy** [ScanNet/ScanNet#89]
Hi currently the server is not available. I am wondering when it will come back? Thank you.

**Comment by Harry-Zhi** [comment]
Same problem here.  

Could you please help making the server back?

**Comment by angrypiggy** [comment]
> Same problem here.
> 
> Could you please help making the server back?

You can download the data as usual. It is just that you cannot browse the query data on the website.

**Comment by Zzh2000** [comment]
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.18 (Ubuntu) Server at kaldir.vc.in.tum.de Port 80
