### ISSUE TITLE
Corrupted data

### ISSUE THREAD

**Issue by martinruenz** [ScanNet/ScanNet#9]
I noticed that there are some camera poses in the dataset with invalid data, with matrices only containing _inf_ values. It’s not a big issue, because this only applies to a small portion of frames, but the issue should at least be documented (I didn’t read about this so far).

Further, I think that many sequences don’t have timestamps, but sometimes random frames seem to have random stamps. Maybe the value wasn’t always initialised?

Here is a small program that can highlight these issues
``` CPP
#include <iostream>
#include "../external/scannet/sensorData.h"

using namespace std;

tuple<bool,bool> analyze_sens(const string& input, bool verbose = false){

    // Input
    if(verbose){
        cout << "Loading data ... ";
        cout.flush();
    }
    ml::SensorData sd(input);
    if(verbose){
        cout << "done!" << endl;
        cout << sd << endl;
    }

    // Stats
    bool ts_d_monotonic = true;
    bool ts_c_monotonic = true;
    bool ts_d_available = false;
    bool ts_c_available = false;
    uint64_t ts_d_last = 0;
    uint64_t ts_c_last = 0;

    bool has_illegal_transformation = false;

    for (size_t i = 0; i < sd.m_frames.size(); i++) {

        // Test timestamps
        const ml::SensorData::RGBDFrame& frame = sd.m_frames[i];
        uint64_t t_d = frame.getTimeStampDepth();
        uint64_t t_c = frame.getTimeStampColor();
        if (t_d > 0) ts_d_available = true;
        if (t_c > 0) ts_c_available = true;
        if (t_d < ts_d_last) ts_d_monotonic = false;
        if (t_c < ts_c_last) ts_c_monotonic = false;
        ts_d_last = t_d;
        ts_c_last = t_c;

        // Test poses
        ml::mat4f t = frame.getCameraToWorld();
        if(t.matrix[15] != 1 || t.matrix[14] != 0 || t.matrix[13] != 0 || t.matrix[12] != 0){
            has_illegal_transformation = true;
            if(verbose)
                cout << "Found illegal transformation at frame " << to_string(i) << ": ["
                     << t.matrix[0] << ", " << t.matrix[1] << ", " << t.matrix[2] << ", " <<t.matrix[3] << "]["
                     << t.matrix[4] << ", " << t.matrix[5] << ", " << t.matrix[6] << ", " <<t.matrix[7] << "]["
                     << t.matrix[8] << ", " << t.matrix[9] << ", " << t.matrix[10] << ", " <<t.matrix[11] << "]["
                     << t.matrix[12] << ", " << t.matrix[13] << ", " << t.matrix[14] << ", " <<t.matrix[15] << "]]" << endl;
        }
    }

    if(verbose){
        cout << "Depth timestamps are monotonic: " << (ts_d_monotonic ? "\x1B[32m yes" : "\x1B[31m no") << "\x1B[0m \n";
        cout << "RGB   timestamps are monotonic: " << (ts_c_monotonic ? "\x1B[32m yes" : "\x1B[31m no") << "\x1B[0m \n";
        cout << "Depth timestamps are available: " << (ts_d_available ? "\x1B[32m yes" : "\x1B[31m no") << "\x1B[0m \n";
        cout << "RGB   timestamps are available: " << (ts_c_available ? "\x1B[32m yes" : "\x1B[31m no") << "\x1B[0m \n";
        cout << "All  camera  poses  were legal: " << (!has_illegal_transformation ? "\x1B[32m yes" : "\x1B[31m no") << "\x1B[0m \n";
        cout << endl;
    }
    return make_tuple(!ts_d_monotonic || !ts_c_monotonic, has_illegal_transformation);
}

int main(int argc, char* argv[])
{
    if(argc < 2 || argc > 3) {
        cout << "A tool to analyse scannet *.sens data.\n\n"
                "Error, invalid arguments.\n"
                "Mandatory: input *.sens file / input *.txt file\n"
                "Optional path to dataset dir (if txt is provided)."
             << endl;
        return 1;
    }

    // Input data
    string filename = argv[1];
    if(filename.substr(filename.find_last_of(".") + 1) == "txt"){
        // Analyse many sens files
        string sequence_name;
        string root = (argc == 3 ? argv[2] : "");
        ifstream in_stream(filename);
        while (getline(in_stream, sequence_name)){
            cout << "Checking " << sequence_name << "...";
            cout.flush();
            tuple<bool,bool> r = analyze_sens(root + "/" + sequence_name + "/" + sequence_name  + ".sens");

            if(get<0>(r))
                cout << "\x1B[31m Timestamp issue \x1B[0m";
            else
                cout << "\x1B[32m Timestamps good \x1B[0m";

            if(get<1>(r))
                cout << "\x1B[31m Pose issue \x1B[0m" << endl;
            else
                cout << "\x1B[32m Poses good \x1B[0m" << endl;
        }
        in_stream.close();
    } else {
        // Analyse single sens files
        analyze_sens(filename, true);
    }


    return 0;
}

```

If you run this script on sequence scene0003_01.sens for example, you get a list of invalid poses, like:

> Found illegal transformation at frame 1054: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1071: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1079: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1080: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1081: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1082: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1083: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1084: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1085: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1086: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1087: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]
> Found illegal transformation at frame 1088: [-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf][-inf, -inf, -inf, -inf]]

Sequence scene0066_00.sens on the other hand has issues with timestamps. You can also run the tool on a list of sequences, giving you output like:
> Checking scene0000_00... Timestamps good  Poses good 
> Checking scene0000_01... Timestamps good  Poses good 
> Checking scene0000_02... Timestamps good  Poses good 
> Checking scene0001_00... Timestamps good  Pose issue 
> Checking scene0001_01... Timestamps good  Pose issue 
> Checking scene0002_00... Timestamps good  Poses good 
> Checking scene0002_01... Timestamps good  Pose issue 
> Checking scene0003_00... Timestamps good  Pose issue 
> Checking scene0003_01... Timestamps good  Pose issue 
> Checking scene0003_02... Timestamps good  Pose issue 
> Checking scene0004_00... Timestamps good  Poses good 
> Checking scene0005_00... Timestamps good  Poses good 
...

Thanks for providing this great dataset by the way!

**Comment by martinruenz** [comment]
There is one more thing I noticed: For the scenes scene0704_* and scene0705_* the intrinsics of the RGB and depth camera are equivalent, namely
> [577.871, 0, 319.5, 0][0, 577.871, 239.5, 0][0, 0, 1, 0][0, 0, 0, 1]]

It looks like the RGB parameters where overwritten accidentally.

**Comment by angeladai** [comment]
Thanks, we've updated the readme regarding the invalid poses.
The timestamps do seem to be caused by an occasional bug during the scan recording.
Regarding the intrinsics, they are similar because these sequences were taken with 640x480 color and depth (see the colorWidth/colorHeight/etc params)

**Comment by shannon112** [comment]
@angeladai Hi, where is the readme updated regarding the invalid poses? I cannot find it in the repo. 
Is this problem solved in current ScanNet dataset? Or we just notice people we might have some invalid poses inside the dataset?
