### ISSUE TITLE
cannot download scannet datasets

### ISSUE THREAD

**Issue by jasmine202106** [ScanNet/ScanNet#91]
when i download scannet datasets, i met one error.
please help me, thanks very much.

$ python -V
Python 3.7.2
$ python download-scannet.py -o ./Scannet_Dataset/
By pressing any key to continue you confirm that you have agreed to the ScanNet terms of use as described at:
http://kaldir.vc.in.tum.de/scannet/ScanNet_TOS.pdf
***
Press any key to continue, or CTRL-C to exit.
Traceback (most recent call last):
  File "download-scannet.py", line 233, in <module>
    if __name__ == "__main__": main()
  File "download-scannet.py", line 142, in main
    key = raw_input('')
NameError: name 'raw_input' is not defined

**Comment by yang-Michael** [comment]
Hello, Can you tell me how to solve this problem?

**Comment by yang-Michael** [comment]
I had solved, thx!

**Comment by ramdrop** [comment]
> I had solved, thx!

@yang-Michael Hi, I encounter the same issue, could you tell me your solution?

**Comment by zhuixunforever** [comment]
I solve this by use python2.7
