### ISSUE TITLE
depth image scale?

### ISSUE THREAD

**Issue by LongruiDong** [ScanNet/ScanNet#96]
Hi
I haven`t find depth value scale from data, how to convert depth value to 'm' ? 

Or does scale equals to 1.0?

**Comment by LongruiDong** [comment]
I check the value of depth image,
```
 0 0 0 0 0 0 0 0 0 0 0 0 0 141 141 142 142 142 142 142 142 144 143 143 143 143 143 143 143 143 143 143 144 144 144 144 144 145 145 145 145 145 146 146 146 146 147 146 146 147 147 148 147 147 147 147 147 147 148 148 148 148 148 149 149......
```

obviously it`s scale does not equal to 1.

**Comment by angeladai** [comment]
The depth shift (1000) is provided in the .sens file, as mentioned here: https://github.com/ScanNet/ScanNet/tree/master/SensReader
